let id = 0;
const radiosinfo = {
  radios: [
    {
      id: ++id,
      name: "home",
      page: "Home",
      backgroundImage: "",
      backgroundColor:
        "radial-gradient(circle, rgba(5,89,0,0.75) 0%, rgba(0,0,0,1) 50%)",
      logo: `/images/logoEPA.png`,
      to: "/",
      shadow: "#000",
      ciudad: "lima",
    },
    {
      id: ++id,
      name: "lanube",
      page: "La nube",
      backgroundImage: `/images/fondo_lanube.jpg`,
      logo: `/images/logo_lanube.png`,
      backgroundColor: "",
      stream: `https://streaming.gometri.com/stream/8025/stream`,
      to: "/radio/lanube",
      shadow: "#f7f7f7",
      ciudad: "lima",
    },
    {
      id: ++id,
      name: "cumbiamix",
      page: "Cumbia Mix",
      backgroundImage: `/images/fondo_cumbiamix.png`,
      logo: `/images/logo_cumbiamix.png`,
      backgroundColor: "",
      stream: `https://streaming.gometri.com/stream/8017/stream`,
      to: "/radio/cumbiamix",
      shadow: "#112555",
      ciudad: "lima",
    },
    {
      id: ++id,
      name: "ondacero",
      page: "Onda Cero",
      backgroundImage: "",
      backgroundColor: "radial-gradient(#FEE248 30%, #FFA01C 100%)",
      logo: `/images/logo_ondaclasico.png`,
      stream: `https://streaming.gometri.com/stream/8011/stream`,
      to: "/radio/ondacero",
      shadow: "#fec233",
      ciudad: "lima",
    },
    {
      id: ++id,
      name: "panamericana",
      page: "Panamericana",
      backgroundImage: `/images/fondo_panamericana.png`,
      logo: `/images/logo_pana.png`,
      backgroundColor: "",
      stream: `https://streaming.gometri.com/stream/8000/stream`,
      to: "/radio/panamericana",
      shadow: "#b70101",
      ciudad: "lima",
    },
    {
      id: ++id,
      name: "oncesesenta",
      page: "1160",
      backgroundImage: "/images/fondo_oncesesenta.png",
      logo: `/images/logo_oncesesenta.png`,
      artistas: `/images/artistas_oncesesenta.png`,
      backgroundColor: "",
      stream: `https://streaming.gometri.com/stream/8021/stream`,
      shadow: "#242424",
      to: "/radio/oncesesenta",
      ciudad: "trujillo",
    },
    {
      id: ++id,
      name: "lavaca",
      page: "Radio la vaca",
      backgroundImage: "",
      logo: `/images/logo_lavaca.png`,
      backgroundColor: "linear-gradient(to left, #000 0%, #000 100%)",
      stream: `https://streaming.gometri.com/stream/8007/stream`,
      to: "/radio/lavaca",
      shadow: "#000",
      ciudad: "chimbote",
    },
    {
      id: ++id,
      name: "radiocomas",
      page: "Radio Comas",
      backgroundImage: "",
      logo: `/images/logo_radiocomas.png`,
      backgroundColor: "linear-gradient(to left, #000 0%, #000 100%)",
      stream: `http://65.60.2.26:8044/stream?icy=http`,
      to: "/radio/radiocomas",
      shadow: "#000",
      ciudad: "cajamarca",
    },
    {
      id: ++id,
      name: "vivafm",
      page: "Viva FM",
      backgroundImage: "",
      logo: `/images/logo_vivafm.png`,
      backgroundColor:
        "radial-gradient(circle, rgba(254,173,3,1) 0%, rgba(254,126,0,1) 100%)",
      stream: `https://tupanel.info:8746/stream`,
      to: "/radio/vivafm",
      shadow: "#ff9c03",
      ciudad: "piura",
    },
    {
      id: ++id,
      name: "exitosa",
      page: "Radio Exitosa",
      backgroundImage: "",
      logo: `/images/logo_exitosa.png`,
      backgroundColor: "linear-gradient(to left, #000 0%, #000 100%)",
      stream: "http://167.114.118.120:7444/stream",
      to: "/radio/exitosa",
      shadow: "#000",
      ciudad: "piura",
    },
    {
      id: ++id,
      name: "ondavip",
      page: "Onda Vip",
      backgroundImage: "",
      logo: `/images/logo_ondavip.png`,
      backgroundColor: "radial-gradient(#452F11 30%, #170F01 100%)",
      artistas: `/images/artistas_vip.png`,
      stream: `https://streaming.gometri.com/stream/8039/stream`,
      to: "/radio/ondavip",
      shadow: "#35240b",
      ciudad: "lima",
    },
    {
      id: ++id,
      name: "ondafeeling",
      page: "Onda Feeling",
      backgroundImage: "",
      logo: `/images/logo_ondafeeling.png`,
      artistas: `/images/artistas_feeling.png`,
      backgroundColor: "radial-gradient(#960C88 30%, #260023 100%)",
      stream: `https://streaming.gometri.com/stream/8035/stream`,
      to: "/radio/ondafeeling",
      shadow: "#6b0861",
      ciudad: "lima",
    },
    {
      id: ++id,
      name: "ondaleyendas",
      page: "Onda Leyendas",
      backgroundImage: `/images/fondo_leyendas.png`,
      logo: `/images/logo_ondaleyendas.png`,
      backgroundColor: "radial-gradient(#452F11 30%, #170F01 100%)",
      artistas: `/images/artistas_leyendas.png`,
      stream: `https://streaming.gometri.com/stream/8033/stream`,
      to: "/radio/ondaleyendas",
      shadow: "#223307",
      ciudad: "cusco",
    },
  ],
};

export default function handler(req, res) {
  res
    .status(200)
    .json(
      req.query.radios == "radios"
        ? radiosinfo
        : radiosinfo.radios.filter((e) => e.name == req.query.radios)[0]
    );
}
