import Head from "next/head";
import Slider from "./Slider";
function Layout(props) {
  return (
    <div>
      <Head>
        <title>next app test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Slider data={props.data} />
        {props.children}
      </main>
    </div>
  );
}

export default Layout;
