import Link from "next/link";
import { useRouter } from "next/router";
import RadiosPageNavbar from "../components/RadiosPageNavbar";
import Navbar from "../components/Navbar";
import Playbar from "../components/Playbar";
import Head from "next/head";
function About() {
  const router = useRouter();
  console.log(router);
  // const handleClick = (e) => window.history.back();
  return (
    <>
      <Head>
        <title>EPA FM - Nosotros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="About">
        <RadiosPageNavbar />
        {/* <Navbar /> */}
      </main>
      <style jsx>{`
        .About {
          width: 100vw;
          height: 100vh;
          background-color: black;
          padding-top: 80px;
        }
      `}</style>
    </>
  );
}

export default About;
